### ISSUE TITLE
Are there any GUIs available?

### ISSUE THREAD

**Issue by slimsag** [mosuka/blast#54]
Hi, just a small question for anyone who might know: Are there any GUIs available for interacting with Blast?

Something like https://github.com/appbaseio/dejavu, but for Blast instead of ES?

**Comment by mosuka** [comment]
Hi @slimsag ,
Unfortunately, there is no GUI.
Since Blast is under development yet, I will consider it later.

**Comment by slimsag** [comment]
Thank you for the information :) I appreciate the help!

**Comment by gedw99** [comment]
@slimsag 
Had a look at dejavu

Its a large code base. Because blast is grpc based, we could code gen much of the code using one of the grpc-web golang libs.   
At that point i would be thinking about if it might be easier to just us golang WASM for the rest of it.

Also,  I am planning to build a Flutter GUI library for blast, so users can use the it in FLutter apps.
I use this: https://github.com/go-flutter-desktop
